name: Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    strategy:
      matrix:
        version: [13.0.1, 14.0.5]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: llvm-${{ matrix.version }}.dockerfile
          tags: ghcr.io/evanrichter/llvm-asan:${{ matrix.version }}

